build: off

# Only build the master branch
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# PR testing doens't increment build number
pull_requests:
  do_not_increment_build_number: true

# Build worker image (VM template)
image: WMF 5

# environment variables
environment:
  # PowerShell Galery encrypted API key
  PSGalleryApiKey:
    secure: /Qj1Xjz6hSCGFUsIi//Tkub6pgdffO01qInzG0sCeafzMJjymzhgUOWFZIWa4L17

# scripts that run after cloning repository
install:
  - ps: .\Posh-YNAB.Build.ps1 -Phase Install

# to run your custom scripts instead of automatic tests
test_script:
  - ps: .\Posh-YNAB.Build.ps1 -Phase Test

# to run your custom scripts instead of automatic tests
deploy_script:
  - ps: .\Posh-YNAB.Build.ps1 -Phase Deploy