version: 0.2

phases:
  install:
    commands:
      - apt-get -qq update
      - apt-get -y install wget
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - dpkg -i packages-microsoft-prod.deb
      - apt-get -y install apt-transport-https
      - apt-get -y update
      - apt-get -y install dotnet-sdk-2.1
  build:
    commands:
        - pwsh ./CodeDeploy.ps1 -Phase Build -ErrorAction Stop